# values/java-app/main/values.yaml

image:
  repository: "europe-docker.pkg.dev/your-project/my-java-repo/java-app"
  tag: "1.1.0" # CI-скрипт затре цю заглушку і вставить реальну версію
  pullPolicy: IfNotPresent
replicaCount: 1
service:
  type: ClusterIP
  port: 8080
