apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-active
  labels: {{ include "myapp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.network.port }}
      targetPort: {{ .Values.network.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "myapp.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-preview
  labels: {{ include "myapp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.network.port }}
      targetPort: {{ .Values.network.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "myapp.selectorLabels" . | nindent 4 }}